# Spanish translation for duplicity
# Copyright (c) 2009 Rosetta Contributors and Canonical Ltd 2009
# This file is distributed under the same license as the duplicity package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2009.
#
msgid ""
msgstr ""
"Project-Id-Version: duplicity\n"
"Report-Msgid-Bugs-To: Kenneth Loafman <kenneth@loafman.com>\n"
"POT-Creation-Date: 2020-03-07 09:49-0600\n"
"PO-Revision-Date: 2018-02-23 13:10+0000\n"
"Last-Translator: Adolfo Jayme <fitoschido@gmail.com>\n"
"Language-Team: Spanish <es@li.org>\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2020-03-18 06:31+0000\n"
"X-Generator: Launchpad (build 3a6db24bbe7280ec09bae73384238390fcc98ad3)\n"

#: ../bin/duplicity:120
msgid "INT intercepted...exiting."
msgstr "INT interceptado... saliendo."

#: ../bin/duplicity:128
#, python-format
msgid "GPG error detail: %s"
msgstr "Detalle de error GPG: %s"

#: ../bin/duplicity:138
#, python-format
msgid "User error detail: %s"
msgstr "Detalle de error del usuario: %s"

#: ../bin/duplicity:148
#, python-format
msgid "Backend error detail: %s"
msgstr "Detalle de error del motor: %s"

#: ../bin/rdiffdir:64 ../duplicity/commandline.py:236
#, python-format
msgid "Error opening file %s"
msgstr "Error al abrir el archivo %s"

#: ../bin/rdiffdir:131
#, python-format
msgid "File %s already exists, will not overwrite."
msgstr "El archivo %s ya existe y no se sobrescribirá."

#: ../duplicity/asyncscheduler.py:70
#, python-format
msgid "instantiating at concurrency %d"
msgstr "crear una instancia en la concurrencia %d"

#: ../duplicity/asyncscheduler.py:97
msgid "inserting barrier"
msgstr "insertando barrera"

#: ../duplicity/asyncscheduler.py:146
msgid "running task synchronously (asynchronicity disabled)"
msgstr "ejecución de tareas de forma sincrónica (asincronía desactivada)"

#: ../duplicity/asyncscheduler.py:152
msgid "scheduling task for asynchronous execution"
msgstr "programación de tareas para la ejecución asíncrona"

#: ../duplicity/asyncscheduler.py:181
msgid "task completed successfully"
msgstr "tarea completada satisfactoriamente"

#: ../duplicity/asyncscheduler.py:192
msgid ""
"a previously scheduled task has failed; propagating the result immediately"
msgstr ""
"una tarea planificada previamente falló; propagando el resultado "
"inmediatamente"

#: ../duplicity/asyncscheduler.py:215 ../duplicity/asyncscheduler.py:236
#, python-format
msgid "active workers = %d"
msgstr "trabajadores activos = %d"

#: ../duplicity/asyncscheduler.py:256
#, python-format
msgid "task execution done (success: %s)"
msgstr "ejecución de la tarea realizada (éxito: %s)"

#: ../duplicity/backend.py:104
#, python-format
msgid "Import of %s %s"
msgstr "Importación de %s %s"

#: ../duplicity/backend.py:213
#, python-format
msgid "Could not initialize backend: %s"
msgstr "No se pudo inicializar el motor: %s"

#: ../duplicity/backend.py:392
#, python-format
msgid "Backtrace of previous error: %s"
msgstr "Volcado de pila del error anterior: %s"

#: ../duplicity/backend.py:408
#, python-format
msgid "Giving up after %s attempts. %s: %s"
msgstr "Desistiendo tras %s intentos. %s: %s"

#: ../duplicity/backend.py:412
#, python-format
msgid "Attempt %s failed. %s: %s"
msgstr "Intento %s fallido. %s: %s"

#: ../duplicity/backend.py:506
#, python-format
msgid "Reading results of '%s'"
msgstr "Leyendo resultados de «%s»"

#: ../duplicity/backend.py:532
#, python-format
msgid "Writing %s"
msgstr "Escribiendo %s"

#: ../duplicity/backend.py:573
#, python-format
msgid "File %s not found locally after get from backend"
msgstr "archivo %s no encontrado localmente tras obtenerlo del servidor"

#: ../duplicity/backends/giobackend.py:109
#, python-format
msgid "Connection failed, please check your password: %s"
msgstr "Falló la conexión, compruebe su contraseña: %s"

#: ../duplicity/backends/multibackend.py:97
#, python-format
msgid "MultiBackend: Could not parse query string %s: %s "
msgstr "MultBackend: no se pudo analizar la cadena de consulta %s: %s "

#: ../duplicity/backends/multibackend.py:106
#, python-format
msgid "MultiBackend: Invalid query string %s: more than one value for %s"
msgstr "MultBackend: cadena de consulta no válida %s: más de un valor para %s"

#: ../duplicity/backends/multibackend.py:111
#, python-format
msgid "MultiBackend: Invalid query string %s: unknown parameter %s"
msgstr "MultBackend: cadena de consulta no válida %s: parámetro desconocido %s"

#: ../duplicity/backends/multibackend.py:161
#: ../duplicity/backends/multibackend.py:166
#, python-format
msgid "MultiBackend: illegal value for %s: %s"
msgstr "MultBackend: valor no permitido para %s: %s"

#: ../duplicity/backends/multibackend.py:177
#, python-format
msgid "MultiBackend: Url %s"
msgstr "MultiBackend: Url %s"

#: ../duplicity/backends/multibackend.py:181
#, python-format
msgid "MultiBackend: Could not load config file %s: %s "
msgstr "MultBackend: no se pudo cargar el archivo de configuración %s: %s "

#: ../duplicity/backends/multibackend.py:190
#, python-format
msgid "MultiBackend: use store %s"
msgstr "MultiBackend: usar almacén %s"

#: ../duplicity/backends/multibackend.py:195
#, python-format
msgid "MultiBackend: set env %s = %s"
msgstr "MultiBackend: set env %s = %s"

#: ../duplicity/backends/multibackend.py:208
#, python-format
msgid "Multibackend: register affinity for prefix %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:249
#, python-format
msgid "MultiBackend: _put: write to store #%s (%s)"
msgstr "MultiBackend: _put: escribir en almacén #%s (%s)"

#: ../duplicity/backends/multibackend.py:262
#, python-format
msgid "MultiBackend: failed to write to store #%s (%s), try #%s, Exception: %s"
msgstr ""
"MultiBackend: falló al escribir en almacén #%s (%s), intenta #%s, Excepción: "
"%s"

#: ../duplicity/backends/multibackend.py:269
#, python-format
msgid "MultiBackend: failed to write %s. Aborting process."
msgstr "MultiBackend: falló al escribir %s. Abortando el proceso."

#: ../duplicity/backends/multibackend.py:276
#, python-format
msgid ""
"MultiBackend: failed to write %s. Tried all backing stores and none succeeded"
msgstr ""
"MultiBackend: falló al escribir %s. Se probaron todos los almacenes de "
"copias y ninguno funcionó"

#: ../duplicity/backends/multibackend.py:295
#, python-format
msgid "MultiBackend: failed to get %s to %s from %s"
msgstr "MultiBackend: falló al obtener %s a %s de %s"

#: ../duplicity/backends/multibackend.py:298
#, python-format
msgid ""
"MultiBackend: failed to get %s. Tried all backing stores and none succeeded"
msgstr ""
"MultiBackend: falló al obtener %s. Se probaron todos los almacenes de copias "
"y ninguno funcionó"

#: ../duplicity/backends/multibackend.py:308
#, python-format
msgid "MultiBackend: %s: %d files"
msgstr ""

#: ../duplicity/backends/multibackend.py:311
#, python-format
msgid "Exception during list of %s: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:318
#, python-format
msgid "MultiBackend: combined list: %s"
msgstr "MultiBackend: lista combinada: %s"

#: ../duplicity/backends/multibackend.py:346
#, python-format
msgid "MultiBackend: failed to delete %s from %s"
msgstr "MultiBackend: falló al eliminar %s de %s"

#: ../duplicity/backends/multibackend.py:350
#, python-format
msgid ""
"MultiBackend: failed to delete %s. Tried all backing stores and none "
"succeeded"
msgstr ""
"MultiBackend: falló al eliminar %s. Se probaron todos los almacenes de "
"copias y ninguno funcionó"

#: ../duplicity/backends/pydrivebackend.py:150
#, python-format
msgid "PyDrive backend: multiple files called '%s'."
msgstr "PyDrive backend: se llamaron múltiples archivos «%s»."

#: ../duplicity/backends/webdavbackend.py:66
msgid "Missing socket or ssl python modules."
msgstr "Faltan los módulos de Python «socket» o «ssl»."

#: ../duplicity/backends/webdavbackend.py:84
#, python-format
msgid "Cacert database file '%s' is not readable."
msgstr "Archivo de base de datos Cacert «%s» ilegible."

#: ../duplicity/backends/webdavbackend.py:105
msgid ""
"Option '--ssl-cacert-path' is not supported with python 2.7.8 and below."
msgstr ""
"Opción «--ssl-cacert-path» no es compatible con python 2.7.8 y anterior."

#: ../duplicity/backends/webdavbackend.py:109
#, python-format
msgid ""
"For certificate verification with python 2.7.8 or earlier a cacert database\n"
"file is needed in one of these locations: %s\n"
"Hints:\n"
"Consult the man page, chapter 'SSL Certificate Verification'.\n"
"Consider using the options --ssl-cacert-file, --ssl-no-check-certificate ."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:155
#, python-format
msgid "Using WebDAV protocol %s"
msgstr "Usando protocolo WebDAV %s"

#: ../duplicity/backends/webdavbackend.py:156
#, python-format
msgid "Using WebDAV host %s port %s"
msgstr "Usando servidor WebDAV %s puerto %s"

#: ../duplicity/backends/webdavbackend.py:158
#, python-format
msgid "Using WebDAV directory %s"
msgstr "Usando directorio de WebDAV %s"

#: ../duplicity/backends/webdavbackend.py:189
#, python-format
msgid "WebDAV create connection on '%s'"
msgstr "Conexión para creación de WebDAV en «%s»"

#: ../duplicity/backends/webdavbackend.py:200
#, python-format
msgid "WebDAV Unknown URI scheme: %s"
msgstr "Esquema de URI WebDAV desconocido: %s"

#: ../duplicity/backends/webdavbackend.py:219
#, python-format
msgid "WebDAV %s %s request with headers: %s "
msgstr "WebDAV %s %s petición con encabezados: %s "

#: ../duplicity/backends/webdavbackend.py:220
#: ../duplicity/backends/webdavbackend.py:243
#, python-format
msgid "WebDAV data length: %s "
msgstr "Longitud de datos de WebDAV: %s "

#: ../duplicity/backends/webdavbackend.py:223
#, python-format
msgid "WebDAV response status %s with reason '%s'."
msgstr "Estado de respuesta WebDAV %s con razón «%s»."

#: ../duplicity/backends/webdavbackend.py:229
#, python-format
msgid "WebDAV redirect to: %s "
msgstr "WebDAV redigir a: %s "

#: ../duplicity/backends/webdavbackend.py:231
msgid "WebDAV redirected 10 times. Giving up."
msgstr "WebDAV redirigido 10 veces. Abandonando."

#: ../duplicity/backends/webdavbackend.py:236
msgid "WebDAV missing location header in redirect response."
msgstr ""
"A WebDAV le falta la cabecera de ubicación en la respuesta de redirección."

#: ../duplicity/backends/webdavbackend.py:241
msgid "WebDAV retry request with authentification headers."
msgstr "Petición de reintento de WebDAV con encabezados de autentificación."

#: ../duplicity/backends/webdavbackend.py:242
#, python-format
msgid "WebDAV %s %s request2 with headers: %s "
msgstr "WebDAV %s %s solicitud2 con encabezados: %s "

#: ../duplicity/backends/webdavbackend.py:246
#, python-format
msgid "WebDAV response2 status %s with reason '%s'."
msgstr "WebDAV respuesta2 estado %s con motivo «%s»."

#: ../duplicity/backends/webdavbackend.py:263
msgid ""
"python-kerberos needed to use kerberos                           "
"authorization, falling back to basic auth."
msgstr ""
"python-kerberos necesitó usar la autorización kerberos, volviendo a la "
"autorización básica."

#: ../duplicity/backends/webdavbackend.py:267
#, python-format
msgid ""
"Kerberos authorization failed: %s.                          Falling back to "
"basic auth."
msgstr "Falló autorización Kerberos: %s. Volviendo a autorización básica."

#: ../duplicity/backends/webdavbackend.py:365
#, python-format
msgid "Creating missing directory %s"
msgstr "Creando directorio que falta %s"

#: ../duplicity/backends/webdavbackend.py:369
#, python-format
msgid "WebDAV MKCOL %s failed: %s %s"
msgstr "WebDAV MKCOL %s falló: %s %s"

#: ../duplicity/backends/webdavbackend.py:382
#, python-format
msgid "WebDAV path decoding and translation: %s -> %s"
msgstr "Descodificación y traducción de rutas de WebDAV: %s → %s"

#: ../duplicity/backends/webdavbackend.py:427
#, python-format
msgid "WebDAV GET Bad status code %s reason %s."
msgstr "WebDAV GET Mal código de estado %s motivo %s."

#: ../duplicity/backends/webdavbackend.py:449
#, python-format
msgid "WebDAV PUT Bad status code %s reason %s."
msgstr "WebDAV PUT Mal código de estado %s motivo %s."

#: ../duplicity/backends/webdavbackend.py:469
#, python-format
msgid "WebDAV DEL Bad status code %s reason %s."
msgstr "WebDAV DEL Mal código de estado %s motivo %s."

#: ../duplicity/commandline.py:79
#, python-format
msgid ""
"Warning: Option %s is pending deprecation and will be removed in a future "
"release.\n"
"Use of default filenames is strongly suggested."
msgstr ""
"Aviso: la opción %s está pendiente de desaprobación y se quitará en una "
"versión futura.\n"
"El uso de nombres de archivo predeterminados es muy recomendable."

#: ../duplicity/commandline.py:86
#, python-format
msgid ""
"Warning: Option %s is pending deprecation and will be removed in a future "
"release.\n"
"--include-filelist and --exclude-filelist now accept globbing characters and "
"should be used instead."
msgstr ""
"Aviso: la opción %s está pendiente de ser obsoletada y se eliminará en una "
"versión futura.\n"
"--include-filelist y --exclude-filelist aceptan ahora caracteres de "
"englobamiento y se deberían usar en su lugar."

#: ../duplicity/commandline.py:96
#, python-format
msgid ""
"Warning: Option %s is pending deprecation and will be removed in a future "
"release.\n"
"On many GNU/Linux systems, stdin is represented by /dev/stdin and\n"
"--include-filelist=/dev/stdin or --exclude-filelist=/dev/stdin could\n"
"be used as a substitute."
msgstr ""
"Aviso: la opción %s está pendiente de ser obsoletada y se eliminará en una "
"versión futura.\n"
"En muchos sistemas GNU/Linux, stdin se representa por /dev/stdin y\n"
"se podría usar --include-filelist=/dev/stdin o --exclude-filelist=/dev/stdin "
"como\n"
"un sustituto."

#. Used in usage help to represent a Unix-style path name. Example:
#. --archive-dir <path>
#: ../duplicity/commandline.py:257 ../duplicity/commandline.py:267
#: ../duplicity/commandline.py:288 ../duplicity/commandline.py:359
#: ../duplicity/commandline.py:377 ../duplicity/commandline.py:609
#: ../duplicity/commandline.py:642 ../duplicity/commandline.py:855
msgid "path"
msgstr "ruta"

#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#. Used in usage help to represent an ID for a hidden GnuPG key. Example:
#. --hidden-encrypt-key <gpg_key_id>
#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#: ../duplicity/commandline.py:283 ../duplicity/commandline.py:290
#: ../duplicity/commandline.py:383 ../duplicity/commandline.py:593
#: ../duplicity/commandline.py:828
msgid "gpg-key-id"
msgstr "gpg-key-id"

#. Used in usage help to represent a "glob" style pattern for
#. matching one or more files, as described in the documentation.
#. Example:
#. --exclude <shell_pattern>
#: ../duplicity/commandline.py:298 ../duplicity/commandline.py:408
#: ../duplicity/commandline.py:878
msgid "shell_pattern"
msgstr "shell_pattern"

#. Used in usage help to represent the name of a file. Example:
#. --log-file <filename>
#: ../duplicity/commandline.py:304 ../duplicity/commandline.py:313
#: ../duplicity/commandline.py:320 ../duplicity/commandline.py:410
#: ../duplicity/commandline.py:417 ../duplicity/commandline.py:430
#: ../duplicity/commandline.py:824
msgid "filename"
msgstr "nombre de archivo"

#. Used in usage help to represent a regular expression (regexp).
#: ../duplicity/commandline.py:327 ../duplicity/commandline.py:421
msgid "regular_expression"
msgstr "expresión regular"

#. Used in usage help to represent a time spec for a previous
#. point in time, as described in the documentation. Example:
#. duplicity remove-older-than time [options] target_url
#: ../duplicity/commandline.py:331 ../duplicity/commandline.py:371
#: ../duplicity/commandline.py:497 ../duplicity/commandline.py:910
msgid "time"
msgstr "hora"

#. Used in usage help. (Should be consistent with the "Options:"
#. header.) Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:379 ../duplicity/commandline.py:477
#: ../duplicity/commandline.py:500 ../duplicity/commandline.py:601
#: ../duplicity/commandline.py:843
msgid "options"
msgstr "opciones"

#: ../duplicity/commandline.py:394
#, python-format
msgid ""
"Running in 'ignore errors' mode due to %s; please re-consider if this was "
"not intended"
msgstr ""
"Ejecutando en modo «ignore errors» debido a %s; reconsidere esta opción si "
"no es su intención"

#. Used in usage help to represent an imap mailbox
#: ../duplicity/commandline.py:406
msgid "imap_mailbox"
msgstr "imap_mailbox"

#: ../duplicity/commandline.py:424
msgid "file_descriptor"
msgstr "file_descriptor"

#. Used in usage help to represent a desired number of
#. something. Example:
#. --num-retries <number>
#: ../duplicity/commandline.py:435 ../duplicity/commandline.py:457
#: ../duplicity/commandline.py:474 ../duplicity/commandline.py:483
#: ../duplicity/commandline.py:533 ../duplicity/commandline.py:538
#: ../duplicity/commandline.py:542 ../duplicity/commandline.py:561
#: ../duplicity/commandline.py:567 ../duplicity/commandline.py:571
#: ../duplicity/commandline.py:637 ../duplicity/commandline.py:838
msgid "number"
msgstr "número"

#. Used in usage help (noun)
#: ../duplicity/commandline.py:438
msgid "backup name"
msgstr "nombre de respaldo"

#: ../duplicity/commandline.py:556
msgid "policy"
msgstr ""

#: ../duplicity/commandline.py:574
msgid "Hot|Cool|Archive"
msgstr ""

#. noun
#: ../duplicity/commandline.py:577 ../duplicity/commandline.py:580
#: ../duplicity/commandline.py:809
msgid "command"
msgstr "orden"

#: ../duplicity/commandline.py:583
msgid "pyrax|cloudfiles"
msgstr "pyrax|cloudfiles"

#: ../duplicity/commandline.py:604
msgid "pem formatted bundle of certificate authorities"
msgstr "paquete formateado pem de entidades de certificación"

#: ../duplicity/commandline.py:605
msgid "path to a folder with certificate authority files"
msgstr "ruta a una carpeta con archivos de autoridad de certificados"

#. Used in usage help. Example:
#. --timeout <seconds>
#. Used in usage help. Example:
#. --backend-retry-delay <seconds>
#. Used in usage help. Example:
#. --timeout <seconds>
#: ../duplicity/commandline.py:614 ../duplicity/commandline.py:648
#: ../duplicity/commandline.py:872
msgid "seconds"
msgstr "segundos"

#. abbreviation for "character" (noun)
#: ../duplicity/commandline.py:620 ../duplicity/commandline.py:806
msgid "char"
msgstr "carácter"

#: ../duplicity/commandline.py:772
#, python-format
msgid "Using archive dir: %s"
msgstr "Usando directorio de archivador: %s"

#: ../duplicity/commandline.py:773
#, python-format
msgid "Using backup name: %s"
msgstr "Usando nombre de copia de seguridad: %s"

#: ../duplicity/commandline.py:780
#, python-format
msgid "Command line error: %s"
msgstr "Error de línea de órdenes: %s"

#: ../duplicity/commandline.py:781
msgid "Enter 'duplicity --help' for help screen."
msgstr "Introduzca «duplicity --help» para tener ayuda en pantalla."

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other_host[:port]//absolute_path
#: ../duplicity/commandline.py:794
msgid "absolute_path"
msgstr "ruta_absoluta"

#. Used in usage help. Example:
#. tahoe://alias/some_dir
#: ../duplicity/commandline.py:798
msgid "alias"
msgstr "alias"

#. Used in help to represent a "bucket name" for Amazon Web
#. Services' Simple Storage Service (S3). Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:803
msgid "bucket_name"
msgstr "nombre_cubo"

#. Used in usage help to represent the name of a container in
#. Amazon Web Services' Cloudfront. Example:
#. cf+http://container_name
#: ../duplicity/commandline.py:814
msgid "container_name"
msgstr "nombre_contenedor"

#. noun
#: ../duplicity/commandline.py:817
msgid "count"
msgstr "recuento"

#. Used in usage help to represent the name of a file directory
#: ../duplicity/commandline.py:820
msgid "directory"
msgstr "directorio"

#. Used in usage help, e.g. to represent the name of a code
#. module. Example:
#. rsync://user[:password]@other.host[:port]::/module/some_dir
#: ../duplicity/commandline.py:833
msgid "module"
msgstr "módulo"

#. Used in usage help to represent an internet hostname. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:847
msgid "other.host"
msgstr "otro.host"

#. Used in usage help. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:851
msgid "password"
msgstr "contraseña"

#. Used in usage help to represent a TCP port number. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:859
msgid "port"
msgstr "puerto"

#. Used in usage help. This represents a string to be used as a
#. prefix to names for backup files created by Duplicity. Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:864
msgid "prefix"
msgstr "prefijo"

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other.host[:port]/relative_path
#: ../duplicity/commandline.py:868
msgid "relative_path"
msgstr "ruta_relativa"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. Example:
#. file:///some_dir
#: ../duplicity/commandline.py:883
msgid "some_dir"
msgstr "algun_dir"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory where files will be
#. coming FROM. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:889
msgid "source_dir"
msgstr "dir_origen"

#. Used in usage help to represent a URL files will be coming
#. FROM. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:894
msgid "source_url"
msgstr "url_origen"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. where files will be
#. going TO. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:900
msgid "target_dir"
msgstr "dir_objetivo"

#. Used in usage help to represent a URL files will be going TO.
#. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:905
msgid "target_url"
msgstr "url_objetivo"

#. Used in usage help to represent a user name (i.e. login).
#. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:915
msgid "user"
msgstr "usuario"

#. account id for b2. Example: b2://account_id@bucket/
#: ../duplicity/commandline.py:918
msgid "account_id"
msgstr "id_cuenta"

#. application_key for b2.
#. Example: b2://account_id:application_key@bucket/
#: ../duplicity/commandline.py:922
msgid "application_key"
msgstr "clave_aplicación"

#. remote name for rclone.
#. Example: rclone://remote:/some_dir
#: ../duplicity/commandline.py:926 ../duplicity/dup_collections.py:511
msgid "remote"
msgstr "remoto"

#. Header in usage help
#: ../duplicity/commandline.py:945
msgid "Backends and their URL formats:"
msgstr "Motores y sus formatos de URL:"

#. Header in usage help
#: ../duplicity/commandline.py:978
msgid "Commands:"
msgstr "Órdenes:"

#: ../duplicity/commandline.py:1003
#, python-format
msgid "Specified archive directory '%s' does not exist, or is not a directory"
msgstr "El directorio del archivador «%s» no existe, o no es un directorio"

#: ../duplicity/commandline.py:1012
#, python-format
msgid ""
"Sign key should be an 8, 16 alt. 40 character hex string, like 'AA0E73D2'.\n"
"Received '%s' instead."
msgstr ""
"La clave de firma debería ser una cadena de 8, 16 o 40 caracteres "
"hexadecimales , como «AA0E732D2».\n"
"Se ha recibido «%s» en su lugar."

#: ../duplicity/commandline.py:1072
#, python-format
msgid ""
"Restore destination directory %s already exists.\n"
"Will not overwrite."
msgstr ""
"Restaurar directorio de destino %s ya existe.\n"
"No sobrescribir."

#: ../duplicity/commandline.py:1077
#, python-format
msgid "Verify directory %s does not exist"
msgstr "El directorio verificado %s no existe"

#: ../duplicity/commandline.py:1083
#, python-format
msgid "Backup source directory %s does not exist."
msgstr "El directorio de origen de respaldo %s no existe."

#: ../duplicity/commandline.py:1114
#, python-format
msgid "Command line warning: %s"
msgstr "Aviso de línea de órdenes: %s"

#: ../duplicity/commandline.py:1114
msgid ""
"Selection options --exclude/--include\n"
"currently work only when backing up,not restoring."
msgstr ""
"Las opciones de selección --exclude/--include\n"
"actualmente funcionan solo cuando se respalda no al restaurar."

#: ../duplicity/commandline.py:1150
#, python-format
msgid "GPG binary is %s, version %s"
msgstr "El binario de GPG es %s, versión %s"

#: ../duplicity/commandline.py:1177
#, python-format
msgid ""
"Bad URL '%s'.\n"
"Examples of URL strings are \"scp://user@host.net:1234/path\" and\n"
"\"file:///usr/local\".  See the man page for more information."
msgstr ""
"URL erróneo «%s».\n"
"Ejemplos de cadenas de URL son «scp://user@host.net:1234/path» \n"
"y «file:///usr/local». Ver el manual para más información."

#: ../duplicity/commandline.py:1207
msgid "Main action: "
msgstr "Acción principal: "

#: ../duplicity/diffdir.py:115 ../duplicity/diffdir.py:418
#, python-format
msgid "Error %s getting delta for %s"
msgstr "Error %s consiguiendo el delta para %s"

#: ../duplicity/diffdir.py:130
#, python-format
msgid "Getting delta of %s and %s"
msgstr "Consiguiendo el delta de %s y %s"

#: ../duplicity/diffdir.py:181
#, python-format
msgid "A %s"
msgstr "A %s"

#: ../duplicity/diffdir.py:188
#, python-format
msgid "M %s"
msgstr "M %s"

#: ../duplicity/diffdir.py:210
#, python-format
msgid "Comparing %s and %s"
msgstr "Comparando %s y %s"

#: ../duplicity/diffdir.py:218
#, python-format
msgid "D %s"
msgstr "D %s"

#: ../duplicity/dup_collections.py:180 ../duplicity/dup_collections.py:194
#, python-format
msgid "BackupSet.delete: missing %s"
msgstr "BackupSet.delete: falta %s"

#: ../duplicity/dup_collections.py:219
msgid "Fatal Error: No manifests found for most recent backup"
msgstr ""
"Error fatal: no se encontraron manifiestos para el respaldo más reciente"

#: ../duplicity/dup_collections.py:228
msgid ""
"Fatal Error: Remote manifest does not match local one.  Either the remote "
"backup set or the local archive directory has been corrupted."
msgstr ""
"Error fatal: el manifiesto remoto no coincide con el local. Ni la "
"configuración de copia de seguridad remota o el directorio del archivo local "
"está dañado."

#: ../duplicity/dup_collections.py:236
msgid "Fatal Error: Neither remote nor local manifest is readable."
msgstr "Error fatal: ni el manifiesto remoto ni el local son legibles"

#: ../duplicity/dup_collections.py:247
#, python-format
msgid "Processing local manifest %s (%s)"
msgstr "Procesando manifiesto local %s (%s)"

#: ../duplicity/dup_collections.py:259
#, python-format
msgid "Error processing remote manifest (%s): %s"
msgstr "Error al procesar el manifiesto remoto (%s): %s"

#: ../duplicity/dup_collections.py:262
#, python-format
msgid "Processing remote manifest %s (%s)"
msgstr "Procesando manifiesto remoto %s (%s)"

#: ../duplicity/dup_collections.py:358
msgid "Preferring Backupset over previous one!"
msgstr "Preferir la configuración de copia de seguridad previa"

#: ../duplicity/dup_collections.py:361
#, python-format
msgid "Ignoring incremental Backupset (start_time: %s; needed: %s)"
msgstr ""
"Ignorar la configuración de copia de seguridad incremental (start_time: %s; "
"necesaria: %s)"

#: ../duplicity/dup_collections.py:366
#, python-format
msgid "Added incremental Backupset (start_time: %s / end_time: %s)"
msgstr ""
"Añadida configuración de copia de seguridad incremental (start_time: %s / "
"end_time: %s)"

#: ../duplicity/dup_collections.py:436
msgid "Chain start time: "
msgstr "Hora de inicio de la cadena: "

#: ../duplicity/dup_collections.py:437
msgid "Chain end time: "
msgstr "Hora de terminación de la cadena: "

#: ../duplicity/dup_collections.py:438
#, python-format
msgid "Number of contained backup sets: %d"
msgstr "Número de conjuntos de respaldo contenidos: %d"

#: ../duplicity/dup_collections.py:440
#, python-format
msgid "Total number of contained volumes: %d"
msgstr "Número total de volúmenes contenidos: %d"

#: ../duplicity/dup_collections.py:442 ../duplicity/dup_collections.py:1231
msgid "Type of backup set:"
msgstr "Tipo de conjunto de respaldo"

#: ../duplicity/dup_collections.py:442 ../duplicity/dup_collections.py:1231
msgid "Time:"
msgstr "Hora:"

#: ../duplicity/dup_collections.py:442
msgid "Num volumes:"
msgstr "Número de volúmenes:"

#: ../duplicity/dup_collections.py:446 ../duplicity/dup_collections.py:1237
msgid "Full"
msgstr "Completo"

#: ../duplicity/dup_collections.py:449 ../duplicity/dup_collections.py:1239
msgid "Incremental"
msgstr "Incremental"

#: ../duplicity/dup_collections.py:509
msgid "local"
msgstr "local"

#: ../duplicity/dup_collections.py:666
msgid "Collection Status"
msgstr "Estado de la colección"

#: ../duplicity/dup_collections.py:668
#, python-format
msgid "Connecting with backend: %s"
msgstr "Conectar con el motor: %s"

#: ../duplicity/dup_collections.py:670
#, python-format
msgid "Archive dir: %s"
msgstr "Directorio de archivador: %s"

#: ../duplicity/dup_collections.py:673
#, python-format
msgid "Found %d secondary backup chain."
msgid_plural "Found %d secondary backup chains."
msgstr[0] "Se encontró %d cadena de respaldo secundaria"
msgstr[1] "Se encontraron %d cadenas de respaldo secundaria"

#: ../duplicity/dup_collections.py:678
#, python-format
msgid "Secondary chain %d of %d:"
msgstr "Cadena secundaria %d de %d:"

#: ../duplicity/dup_collections.py:684
msgid "Found primary backup chain with matching signature chain:"
msgstr ""
"Se encontró cadena de copia de seguridad primaria con cadena de firma "
"coincidente:"

#: ../duplicity/dup_collections.py:688
msgid "No backup chains with active signatures found"
msgstr "No encontró cadenas con firmas activas"

#: ../duplicity/dup_collections.py:691
#, python-format
msgid "Also found %d backup set not part of any chain,"
msgid_plural "Also found %d backup sets not part of any chain,"
msgstr[0] ""
"También encontró %d configuración de copia de seguridad no incluida en "
"niguna cadena,"
msgstr[1] ""
"También encontró %d configuraciones de copia de seguridad no incluidas en "
"niguna cadena,"

#: ../duplicity/dup_collections.py:695
#, python-format
msgid "and %d incomplete backup set."
msgid_plural "and %d incomplete backup sets."
msgstr[0] "y %d conjunto de respaldo incompleto"
msgstr[1] "y %d conjuntos de respaldos incompletos"

#. "cleanup" is a hard-coded command, so do not translate it
#: ../duplicity/dup_collections.py:700
msgid "These may be deleted by running duplicity with the \"cleanup\" command."
msgstr "Esto se puede eliminar ejecutando duplicity con la orden «cleanup»"

#: ../duplicity/dup_collections.py:703
msgid "No orphaned or incomplete backup sets found."
msgstr "No se han encontrado respaldos huérfanos o incompletos."

#: ../duplicity/dup_collections.py:719
#, python-format
msgid "%d file exists on backend"
msgid_plural "%d files exist on backend"
msgstr[0] "%d archivo existe en la copia de seguridad"
msgstr[1] "%d archivos existen en la copia de seguridad"

#: ../duplicity/dup_collections.py:729
#, python-format
msgid "%d file exists in cache"
msgid_plural "%d files exist in cache"
msgstr[0] "existe %d arcvhivo en cahé"
msgstr[1] "existen %d arcvhivos en cahé"

#: ../duplicity/dup_collections.py:782
msgid "Warning, discarding last backup set, because of missing signature file."
msgstr ""
"Aviso, descartando el último conjunto de respaldo, debido a la falta archivo "
"de firma."

#: ../duplicity/dup_collections.py:805
msgid "Warning, found the following local orphaned signature file:"
msgid_plural "Warning, found the following local orphaned signature files:"
msgstr[0] "Aviso, encontró el siguiente archivo huérfano local con firma:"
msgstr[1] ""
"Aviso, encontró los siguientes archivos huérfanos locales con firma:"

#: ../duplicity/dup_collections.py:814
msgid "Warning, found the following remote orphaned signature file:"
msgid_plural "Warning, found the following remote orphaned signature files:"
msgstr[0] "Aviso, encontró el siguiente archivo huérfano remoto con firma:"
msgstr[1] ""
"Aviso, encontró los siguientes archivos huérfanos remotos con firma:"

#: ../duplicity/dup_collections.py:823
msgid "Warning, found signatures but no corresponding backup files"
msgstr ""
"Aviso, se encontraron firmas pero no coinciden con los archivos de copia de "
"seguridad"

#: ../duplicity/dup_collections.py:827
msgid ""
"Warning, found incomplete backup sets, probably left from aborted session"
msgstr ""
"Aviso, encontró conjuntos de copia de seguridad incompletos, probablemente "
"de la sesión abortada"

#: ../duplicity/dup_collections.py:831
msgid "Warning, found the following orphaned backup file:"
msgid_plural "Warning, found the following orphaned backup files:"
msgstr[0] "Aviso, se encuentra el siguiente archivo de respaldo huérfano:"
msgstr[1] ""
"Aviso, se encuentran los siguientes archivos de copia de seguridad huérfanos:"

#: ../duplicity/dup_collections.py:848
#, python-format
msgid "Extracting backup chains from list of files: %s"
msgstr "Extrayendo cadenas de respaldo de la lista de archivos: %s"

#: ../duplicity/dup_collections.py:860
#, python-format
msgid "File %s is part of known set"
msgstr "El archivo %s es parte del conjunto conocido"

#: ../duplicity/dup_collections.py:863
#, python-format
msgid "File %s is not part of a known set; creating new set"
msgstr ""
"El archivo %s no es parte de un conjunto conocido; creando un conjunto nuevo"

#: ../duplicity/dup_collections.py:868
#, python-format
msgid "Ignoring file (rejected by backup set) '%s'"
msgstr "Ignorando archivo (rechazado por el conjunto) «%s»"

#: ../duplicity/dup_collections.py:884
#, python-format
msgid "Found backup chain %s"
msgstr "Se encontró una cadena de respaldo %s"

#: ../duplicity/dup_collections.py:889
#, python-format
msgid "Added set %s to pre-existing chain %s"
msgstr "conjunto %s añadido a la cadena %s preexistente"

#: ../duplicity/dup_collections.py:893
#, python-format
msgid "Found orphaned set %s"
msgstr "Se encontró un conjunto huérfano %s"

#: ../duplicity/dup_collections.py:1043
#, python-format
msgid ""
"No signature chain for the requested time. Using oldest available chain, "
"starting at time %s."
msgstr ""
"No hay cadena de firmas disponibles para la hora solicitada. Se está usando "
"la cadena más antigua disponible, que comienza en %s."

#: ../duplicity/dup_collections.py:1229
#, python-format
msgid "File: %s"
msgstr "Archivo: %s"

#: ../duplicity/dup_collections.py:1230
#, python-format
msgid "Total number of backup: %d"
msgstr "Número total de copias de seguridad: %d"

#: ../duplicity/dup_collections.py:1231
msgid "Type of file change:"
msgstr "Tipo de cambio de archivo:"

#: ../duplicity/dup_main.py:121
msgid "Reuse configured PASSPHRASE as SIGN_PASSPHRASE"
msgstr "Reusar configurar PASSPHRASE como SIGN_PASSPHRASE"

#: ../duplicity/dup_main.py:128
msgid "Reuse configured SIGN_PASSPHRASE as PASSPHRASE"
msgstr "Reusar configurar SIGN_PASSPHRASE como PASSPHRASE"

#: ../duplicity/dup_main.py:167
msgid "PASSPHRASE variable not set, asking user."
msgstr "Variable PASSPHRASE no establecida, preguntar al usuario."

#: ../duplicity/dup_main.py:182
msgid "GnuPG passphrase for signing key:"
msgstr "Frase de paso GnuPG para clave de firmada:"

#: ../duplicity/dup_main.py:187
msgid "GnuPG passphrase:"
msgstr "Frase de contraseña GnuPG:"

#: ../duplicity/dup_main.py:192
msgid "Retype passphrase for signing key to confirm: "
msgstr "Vuelva a teclear la frase de paso de la clave firmada para confirmar: "

#: ../duplicity/dup_main.py:194
msgid "Retype passphrase to confirm: "
msgstr "Repita la contraseña para confirmar: "

#: ../duplicity/dup_main.py:197
msgid "First and second passphrases do not match!  Please try again."
msgstr ""
"¡La primera y segunda contraseña no coinciden! Por favor inténtelo de nuevo."

#: ../duplicity/dup_main.py:204
msgid ""
"Cannot use empty passphrase with symmetric encryption!  Please try again."
msgstr ""
"¡No puede usar una contraseña en blanco con cifrado asimétrico! Por favor "
"inténtelo de nuevo."

#: ../duplicity/dup_main.py:261
#, python-format
msgid ""
"File %s complete in backup set.\n"
"Continuing restart on file %s."
msgstr ""
"El archivo %s está competo en el conjunto de respaldo.\n"
"Continuar la restauración en el archivo %s."

#: ../duplicity/dup_main.py:270
#, python-format
msgid ""
"File %s missing in backup set.\n"
"Continuing restart on file %s."
msgstr ""
"El archivo %s  falta en el conjunto de respaldo.\n"
"Reinicio continuo en el archivo %s."

#: ../duplicity/dup_main.py:319
#, python-format
msgid "File %s was corrupted during upload."
msgstr "El archivo %s se ha dañado en la carga."

#: ../duplicity/dup_main.py:359
msgid ""
"Restarting backup, but current encryption settings do not match original "
"settings"
msgstr ""
"Reiniciando copia de respaldo, pero la configuración actual de cifrado no "
"coincide con la configuración original"

#: ../duplicity/dup_main.py:382
#, python-format
msgid "Restarting after volume %s, file %s, block %s"
msgstr "Reiniciando tras volumen %s, archivo %s, bloque %s"

#: ../duplicity/dup_main.py:452
#, python-format
msgid "Processed volume %d"
msgstr "Se procesó el volumen %d"

#: ../duplicity/dup_main.py:602
msgid ""
"Fatal Error: Unable to start incremental backup.  Old signatures not found "
"and incremental specified"
msgstr ""
"Error Fatal: No se puede iniciar respaldo incremental. Firmas de edad y que "
"no se encuentran especificados incremental"

#: ../duplicity/dup_main.py:606
msgid "No signatures found, switching to full backup."
msgstr "Firmas no encontradas, cambiando a un backup completo."

#: ../duplicity/dup_main.py:620
msgid "Backup Statistics"
msgstr "Estadísticas de respaldo"

#: ../duplicity/dup_main.py:726
#, python-format
msgid "%s not found in archive - no files restored."
msgstr "No se encontró %s en el archivador; no se restauró ningún archivo."

#: ../duplicity/dup_main.py:730
msgid "No files found in archive - nothing restored."
msgstr "No se encontraron archivos en el archivador - nada que restaurar."

#: ../duplicity/dup_main.py:763
#, python-format
msgid "Processed volume %d of %d"
msgstr "Volumen procesado %d de %d"

#: ../duplicity/dup_main.py:797
#, python-format
msgid "Invalid data - %s hash mismatch for file:"
msgstr "datos no válidos - %s hash no coincide con archivo:"

#: ../duplicity/dup_main.py:800
#, python-format
msgid "Calculated hash: %s"
msgstr "hash calculado: %s"

#: ../duplicity/dup_main.py:801
#, python-format
msgid "Manifest hash: %s"
msgstr "Manifestar hass: %s"

#: ../duplicity/dup_main.py:844
#, python-format
msgid "Volume was signed by key %s, not %s"
msgstr "El volumen fue firmado por %s clave, no %s"

#: ../duplicity/dup_main.py:876
#, python-format
msgid "Verify complete: %s, %s."
msgstr "Verificación completa: %s, %s."

#: ../duplicity/dup_main.py:877
#, python-format
msgid "%d file compared"
msgid_plural "%d files compared"
msgstr[0] "%d archivo comparado"
msgstr[1] "%d archivos comparados"

#: ../duplicity/dup_main.py:879
#, python-format
msgid "%d difference found"
msgid_plural "%d differences found"
msgstr[0] "%d diferencia encontrada"
msgstr[1] "%d diferencias encontradas"

#: ../duplicity/dup_main.py:898
msgid "No extraneous files found, nothing deleted in cleanup."
msgstr "Ningún archivo raro encontrado, nada borrado al acabar."

#: ../duplicity/dup_main.py:903
msgid "Deleting this file from backend:"
msgid_plural "Deleting these files from backend:"
msgstr[0] "Eliminando este archivo del respaldo:"
msgstr[1] "Eliminando estos archivos de la copia de seguridad:"

#: ../duplicity/dup_main.py:914
msgid "Found the following file to delete:"
msgid_plural "Found the following files to delete:"
msgstr[0] "Encontrado el siguiente archivo a eliminar:"
msgstr[1] "Encontrados los siguientes archivos a eliminar:"

#: ../duplicity/dup_main.py:917
msgid "Run duplicity again with the --force option to actually delete."
msgstr ""
"Ejecutar duplicity de nuevo con la opción --foirce para eliminar realmente."

#: ../duplicity/dup_main.py:960
msgid "There are backup set(s) at time(s):"
msgstr "Hay conjuntos de respaldo con hora:"

#: ../duplicity/dup_main.py:962
msgid "Which can't be deleted because newer sets depend on them."
msgstr ""
"Que no se puede eliminar porque los nuevos conjuntos dependen de ellos."

#: ../duplicity/dup_main.py:966
msgid ""
"Current active backup chain is older than specified time.  However, it will "
"not be deleted.  To remove all your backups, manually purge the repository."
msgstr ""
"La cadena del respaldo activo actual es anterior a la hora especificada, por "
"lo que no se eliminará. Para eliminar todos sus respaldos, purgue "
"manualmente el repositiorio."

#: ../duplicity/dup_main.py:979
msgid "No old backup sets found, nothing deleted."
msgstr "No se encontraron respaldos. nada que eliminar."

#: ../duplicity/dup_main.py:982
msgid "Deleting backup chain at time:"
msgid_plural "Deleting backup chains at times:"
msgstr[0] "Borrando cadena de copias de seguridad en hora:"
msgstr[1] "Borrando cadena de copias de seguridad en horas:"

#: ../duplicity/dup_main.py:994
#, python-format
msgid "Deleting any incremental signature chain rooted at %s"
msgstr "Eliminando cualquier cadena de firmado incremental con origen en %s"

#: ../duplicity/dup_main.py:996
#, python-format
msgid "Deleting any incremental backup chain rooted at %s"
msgstr "Eliminando cualquier copia de seguridad incremental con origen en %s"

#: ../duplicity/dup_main.py:999
#, python-format
msgid "Deleting complete signature chain %s"
msgstr "Borrando cadenas de firmas completas %s"

#: ../duplicity/dup_main.py:1001
#, python-format
msgid "Deleting complete backup chain %s"
msgstr "Borrando cadena de copias de seguridad completas %s"

#: ../duplicity/dup_main.py:1007
msgid "Found old backup chain at the following time:"
msgid_plural "Found old backup chains at the following times:"
msgstr[0] ""
"Se encontró cadena de copias de seguridad antigua en la siguiente hora:"
msgstr[1] ""
"Se encontró cadena de copias de seguridad antigua en las siguientes horas:"

#: ../duplicity/dup_main.py:1011
msgid "Rerun command with --force option to actually delete."
msgstr ""
"Volviendo a ejecutar orden con la opción --force para eliminar realmente."

#: ../duplicity/dup_main.py:1034
msgid "No old backup sets found."
msgstr ""

#: ../duplicity/dup_main.py:1049
#, python-format
msgid "Signature %s already replicated"
msgstr ""

#: ../duplicity/dup_main.py:1056 ../duplicity/dup_main.py:1095
#, python-format
msgid "Replicating %s."
msgstr ""

#: ../duplicity/dup_main.py:1083
#, python-format
msgid "Backupset %s already replicated"
msgstr ""

#: ../duplicity/dup_main.py:1231
#, python-format
msgid "Deleting local %s (not authoritative at backend)."
msgstr "Eliminación local %s (No es una autoridad en el procesamiento)"

#: ../duplicity/dup_main.py:1236
#, python-format
msgid "Unable to delete %s: %s"
msgstr "No se puede eliminar %s: %s"

#: ../duplicity/dup_main.py:1270 ../duplicity/dup_temp.py:271
#, python-format
msgid "Failed to read %s: %s"
msgstr "No se pudo leer %s: %s"

#: ../duplicity/dup_main.py:1284
#, python-format
msgid "Copying %s to local cache."
msgstr "Copiando %s a la caché local."

#: ../duplicity/dup_main.py:1332
msgid "Local and Remote metadata are synchronized, no sync needed."
msgstr ""
"Los metadatos en local y remoto están sincronizados, no es necesario "
"sincronizar."

#: ../duplicity/dup_main.py:1337
msgid "Synchronizing remote metadata to local cache..."
msgstr "Sincronizando metadatos remotos con la caché local..."

#: ../duplicity/dup_main.py:1350
msgid "Sync would copy the following from remote to local:"
msgstr "Sync copiaría lo siguiente de remoto a local:"

#: ../duplicity/dup_main.py:1353
msgid "Sync would remove the following spurious local files:"
msgstr "Sync eliminaría los siguientes archivos locales:"

#: ../duplicity/dup_main.py:1397
msgid "Unable to get free space on temp."
msgstr "Imposible conseguir espacio libre en temp."

#: ../duplicity/dup_main.py:1405
#, python-format
msgid "Temp space has %d available, backup needs approx %d."
msgstr ""
"Espacio temporal tiene %d disponibles, copias de seguridad necesitan "
"aproximadamente %d."

#: ../duplicity/dup_main.py:1408
#, python-format
msgid "Temp has %d available, backup will use approx %d."
msgstr "Temp tiene %d disponible, el respaldo usará aproximadamente %d."

#: ../duplicity/dup_main.py:1416
msgid "Unable to get max open files."
msgstr "No se puede obtener archivos de máxima apertura."

#: ../duplicity/dup_main.py:1420
#, python-format
msgid ""
"Max open files of %s is too low, should be >= 1024.\n"
"Use 'ulimit -n 1024' or higher to correct.\n"
msgstr ""
"El máximo de archivos abiertos %s es demasiado pequeño, debería ser >= "
"1.024.\n"
"Utilice «ulimit -n 1024» o más alto para corregirlo.\n"

#: ../duplicity/dup_main.py:1472
msgid ""
"RESTART: The first volume failed to upload before termination.\n"
"         Restart is impossible...starting backup from beginning."
msgstr ""
"REINICIAR: El primer volumen no se han cargado antes de la terminación.\n"
"         Reiniciar es imposible... iniciando respaldo desde el principio."

#: ../duplicity/dup_main.py:1478
#, python-format
msgid ""
"RESTART: Volumes %d to %d failed to upload before termination.\n"
"         Restarting backup at volume %d."
msgstr ""
"REINICIAR: Volúmenes %d a %d fallaron al cargar antes de terminar.\n"
"         Reiniciar copia de respaldo en el volumen %d."

#: ../duplicity/dup_main.py:1485
#, python-format
msgid ""
"RESTART: Impossible backup state: manifest has %d vols, remote has %d vols.\n"
"         Restart is impossible ... duplicity will clean off the last "
"partial\n"
"         backup then restart the backup from the beginning."
msgstr ""
"REINICIAR: Estado de copia de respaldo no posible: manifesto tiene %d vols, "
"remoto tiene %d vols.\n"
"         Reiniciar no es posible .. duplicity limpiará la última copia de "
"respaldo parcial\n"
"         y reiniciará la copia desde el principio."

#: ../duplicity/dup_main.py:1506
msgid ""
"\n"
"PYTHONOPTIMIZE in the environment causes duplicity to fail to\n"
"recognize its own backups.  Please remove PYTHONOPTIMIZE from\n"
"the environment and rerun the backup.\n"
"\n"
"See https://bugs.launchpad.net/duplicity/+bug/931175\n"
msgstr ""
"\n"
"PYTHONOPTIMIZE en el entorno causa que duplicity falle al\n"
"reconocer sus propias copias de seguridad. Elimine PYTHONOPTIMIZE\n"
"del entorno y vuelva a ejecutar la copia de seguridad.\n"
"\n"
"Consulte https://bugs.launchpad.net/duplicity/+bug/931175\n"

#: ../duplicity/dup_main.py:1529
#, python-format
msgid "Acquiring lockfile %s"
msgstr "Adquiriendo candado %s"

#: ../duplicity/dup_main.py:1587
#, python-format
msgid "Last %s backup left a partial set, restarting."
msgstr ""
"La última copia de seguridad %s dejó una configuración parcial, reiniciar."

#: ../duplicity/dup_main.py:1591
#, python-format
msgid "Cleaning up previous partial %s backup set, restarting."
msgstr ""
"Limpiar la configuración parcial de la copia de seguridad %s previa, "
"reiniciar."

#: ../duplicity/dup_main.py:1603
msgid "Last full backup date:"
msgstr "Fecha del último respaldo completo:"

#: ../duplicity/dup_main.py:1605
msgid "Last full backup date: none"
msgstr "Fecha del último respaldo completo: ninguna"

#: ../duplicity/dup_main.py:1608
msgid "Last full backup is too old, forcing full backup"
msgstr ""
"El último respaldo completo es demasiado viejo, lo que obligó a una copia de "
"seguridad completa"

#: ../duplicity/dup_main.py:1657
msgid ""
"When using symmetric encryption, the signing passphrase must equal the "
"encryption passphrase."
msgstr ""
"Al usar el cifrado simétrico, la contraseña de firmado debe coincidir con la "
"de cifrado."

#: ../duplicity/dup_time.py:63
#, python-format
msgid ""
"Bad interval string \"%s\"\n"
"\n"
"Intervals are specified like 2Y (2 years) or 2h30m (2.5 hours).  The\n"
"allowed special characters are s, m, h, D, W, M, and Y.  See the man\n"
"page for more information."
msgstr ""
"Cadena de intervalo errónea «%s»\n"
"\n"
"Los intervalos son del tipo 2Y (2 años) o 2h30m (2.5 horas). \n"
"Los caracteres especiales permitidos son s, m, h, D, W, M e Y.\n"
"Ver el manual para más información."

#: ../duplicity/dup_time.py:69
#, python-format
msgid ""
"Bad time string \"%s\"\n"
"\n"
"The acceptible time strings are intervals (like \"3D64s\"), w3-datetime\n"
"strings, like \"2002-04-26T04:22:01-07:00\" (strings like\n"
"\"2002-04-26T04:22:01\" are also acceptable - duplicity will use the\n"
"current time zone), or ordinary dates like 2/4/1997 or 2001-04-23\n"
"(various combinations are acceptable, but the month always precedes\n"
"the day)."
msgstr ""
"Cadena de fecha incorrecta «%s»\n"
"\n"
"Las cadenas de fecha aceptable son intervalos (tipo «3D64s»), cadenas w3-"
"datetime\n"
", tipo «2002-04-26T04:22:01-07:00» (cadenas tipo\n"
"«2002-04-26T04:22:01» son aceptables - duplicity usará la zona\n"
"horaria actual), o fecha normales tipo 2/4/1997 o 2001-04-23\n"
"(son aceptables distintas combinaciones, pero el mes debe preceder\n"
" al día siempre)."

#: ../duplicity/gpginterface.py:238
msgid "Threading not available -- zombie processes may appear"
msgstr "Hilo no disponible -- pueden aparecer procesos zombis"

#: ../duplicity/gpginterface.py:705
#, python-format
msgid "GPG process %d terminated before wait()"
msgstr "El proceso GPG %d terminó antes que el procedimiento wait()"

#: ../duplicity/lazy.py:352
#, python-format
msgid "Warning: oldindex %s >= newindex %s"
msgstr "Aviso: índice antiguo %s >= nuevo índice %s"

#: ../duplicity/lazy.py:427
#, python-format
msgid "Error '%s' processing %s"
msgstr "Error «%s» procesando %s"

#: ../duplicity/lazy.py:437
#, python-format
msgid "Skipping %s because of previous error"
msgstr "Omitiendo %s debido al error anterior"

#: ../duplicity/librsync.py:195
msgid ""
"basis_file must be a (true) file or an object whose file attribute is the "
"underlying true file object"
msgstr ""
"basis_file debe ser un archivo (verdadero) o un objeto cuyos atributos de "
"archivo son el objeto del archivo verdadero subyacente"

#: ../duplicity/manifest.py:96
#, python-format
msgid ""
"Fatal Error: Backup source host has changed.\n"
"Current hostname: %s\n"
"Previous hostname: %s"
msgstr ""
"Error fatal: el anfitrión de origen del respaldo ha cambiado.\n"
"Anfitrión actual: %s\n"
"Anfitrión anterior: %s"

#: ../duplicity/manifest.py:103
#, python-format
msgid ""
"Fatal Error: Backup source directory has changed.\n"
"Current directory: %s\n"
"Previous directory: %s"
msgstr ""
"Error fatal: el directorio de origen del respaldo ha cambiado.\n"
"Directorio actual: %s\n"
"Directorio anterior: %s"

#: ../duplicity/manifest.py:113
msgid ""
"Aborting because you may have accidentally tried to backup two different "
"data sets to the same remote location, or using the same archive directory.  "
"If this is not a mistake, use the --allow-source-mismatch switch to avoid "
"seeing this message"
msgstr ""
"Abortar porque puede haber intentado dos conjuntos de datos distintos en la "
"misma ubicación remota por error, o utilizado el mismo directorio de "
"archivo. Sí no es un error, use --allow-source-mismatch para no ver este "
"mensaje"

#: ../duplicity/manifest.py:215
#, python-format
msgid "Found manifest volume %s"
msgstr "Volumen manifest encontrado %s"

#: ../duplicity/manifest.py:222
#, python-format
msgid "Found %s volumes in manifest"
msgstr "Encontrados %s volúmenes en el manifiesto"

#: ../duplicity/manifest.py:239
#, python-format
msgid ""
"Manifest file '%s' is corrupt: File count says %d, File list contains %d"
msgstr ""
"El archivo de manifiesto «%s» está corrupto: El contador de archivos dice "
"%d, La lista de archivos contiene %d"

#: ../duplicity/manifest.py:258
msgid "Manifests not equal because different volume numbers"
msgstr ""
"Los manifiestos no son iguales debido a los diferentes números de volumen"

#: ../duplicity/manifest.py:263
msgid "Manifests not equal because volume lists differ"
msgstr "Los manifiestos no son iguales porque las listas de volúmenes difieren"

#: ../duplicity/manifest.py:268
msgid "Manifests not equal because hosts or directories differ"
msgstr ""
"Los manifiestos no son iguales porque los anfitriones o directorios no "
"coinciden"

#: ../duplicity/manifest.py:425
msgid "Warning, found extra Volume identifier"
msgstr "Aviso, se encontró un identificador de volumen extra"

#: ../duplicity/manifest.py:451
msgid "Other is not VolumeInfo"
msgstr "Otro no es VolumeInfo"

#: ../duplicity/manifest.py:454
msgid "Volume numbers don't match"
msgstr "Los números de volúmenes no coinciden"

#: ../duplicity/manifest.py:457
msgid "start_indicies don't match"
msgstr "start_indicies no coinciden"

#: ../duplicity/manifest.py:460
msgid "end_index don't match"
msgstr "end_index no coinciden"

#: ../duplicity/manifest.py:467
msgid "Hashes don't match"
msgstr "Hashes no coinciden"

#: ../duplicity/patchdir.py:84 ../duplicity/patchdir.py:89
#, python-format
msgid "Patching %s"
msgstr "Parcheando %s"

#: ../duplicity/patchdir.py:550
#, python-format
msgid "Error '%s' patching %s"
msgstr "Error «%s» parcheando %s"

#: ../duplicity/patchdir.py:625
#, python-format
msgid "Writing %s of type %s"
msgstr "Escribiendo %s del tipo %s"

#: ../duplicity/path.py:116
#, python-format
msgid "Warning: %s invalid devnums (0x%X), treating as (0, 0)."
msgstr "Aviso: %s devnums inválidos (0x%X), tratando como (0, 0)."

#: ../duplicity/path.py:245 ../duplicity/path.py:306
#, python-format
msgid "Warning: %s has negative mtime, treating as 0."
msgstr "Aviso: %s tiene mtime negativo, tratando como 0."

#: ../duplicity/path.py:370
msgid "Difference found:"
msgstr "Diferencia encontrada:"

#: ../duplicity/path.py:379
#, python-format
msgid "New file %s"
msgstr "Archiv nuevo %s"

#: ../duplicity/path.py:382
#, python-format
msgid "File %s is missing"
msgstr "Falta el archivo %s"

#: ../duplicity/path.py:385
#, python-format
msgid "File %%s has type %s, expected %s"
msgstr "El archivo %%s tiene el tipo %s, se esperaba %s"

#: ../duplicity/path.py:391 ../duplicity/path.py:417
#, python-format
msgid "File %%s has permissions %s, expected %s"
msgstr "El archivo %%s tiene permisos %s, se esperaba %s"

#: ../duplicity/path.py:396
#, python-format
msgid "File %%s has mtime %s, expected %s"
msgstr "El archivo %%s tiene mtime %s, se esperaba %s"

#: ../duplicity/path.py:404
#, python-format
msgid "Data for file %s is different"
msgstr "Los datos para el archivo %s son diferentes"

#: ../duplicity/path.py:412
#, python-format
msgid "Symlink %%s points to %s, expected %s"
msgstr "El vínculo simbólico %%s apunta a %s, se esperaba %s"

#: ../duplicity/path.py:421
#, python-format
msgid "Device file %%s has numbers %s, expected %s"
msgstr "El archivo de dispositivo %%s tiene números %s, se esperaba %s"

#: ../duplicity/path.py:603
#, python-format
msgid "Making directory %s"
msgstr "Haciendo directorio %s"

#: ../duplicity/path.py:613
#, python-format
msgid "Deleting %s"
msgstr "Borrando %s"

#: ../duplicity/path.py:622
#, python-format
msgid "Touching %s"
msgstr "Tocando %s"

#: ../duplicity/path.py:629
#, python-format
msgid "Deleting tree %s"
msgstr "Eliminando árbol %s"

#: ../duplicity/robust.py:64
#, python-format
msgid "Error listing directory %s"
msgstr "Error al escuchar el directorio %s"

#: ../duplicity/selection.py:121
#, python-format
msgid "Skipping socket %s"
msgstr "Omitiendo el zócalo %s"

#: ../duplicity/selection.py:125
#, python-format
msgid "Error initializing file %s"
msgstr "Error al inicializar el archivo %s"

#: ../duplicity/selection.py:129 ../duplicity/selection.py:154
#: ../duplicity/selection.py:454
#, python-format
msgid "Error accessing possibly locked file %s"
msgstr "Error al acceder a un archivo posiblemente bloqueado %s"

#: ../duplicity/selection.py:169
#, python-format
msgid "Warning: base %s doesn't exist, continuing"
msgstr "Aviso: %s base no existe, continuando"

#: ../duplicity/selection.py:172 ../duplicity/selection.py:190
#: ../duplicity/selection.py:193
#, python-format
msgid "Selecting %s"
msgstr "Seleccionando %s"

#: ../duplicity/selection.py:290
#, python-format
msgid ""
"Fatal Error: The file specification\n"
"    %s\n"
"cannot match any files in the base directory\n"
"    %s\n"
"Useful file specifications begin with the base directory or some\n"
"pattern (such as '**') which matches the base directory."
msgstr ""
"Error fatal: El archivo especificado\n"
"    %s\n"
"no coincide con ningún archivo del directorio principal\n"
"    %s\n"
"Las especificaciones de archivos útiles empiezan con el directorio\n"
"principal o pautas (tipo «**«) que coinciden con el directorio principal."

#: ../duplicity/selection.py:299
#, python-format
msgid ""
"Fatal Error while processing expression\n"
"%s"
msgstr ""
"Error fatal al procesar la expresión\n"
"%s"

#: ../duplicity/selection.py:308
#, python-format
msgid ""
"Last selection expression:\n"
"    %s\n"
"only specifies that files be included.  Because the default is to\n"
"include all files, the expression is redundant.  Exiting because this\n"
"probably isn't what you meant."
msgstr ""
"La última expresión elegida:\n"
"    %s\n"
"solo especifica qué archivos están incluidos. Porque la expresión de serie\n"
"incluye todos los archivos, es redundante. Salir porque probablemente\n"
"no es la opción elegida."

#: ../duplicity/selection.py:364
#, python-format
msgid "Reading globbing filelist %s"
msgstr "Leyendo listado de archivo del recuadro %s"

#: ../duplicity/selection.py:397
#, python-format
msgid "Error compiling regular expression %s"
msgstr "Error al compilar la expresión regular %s"

#: ../duplicity/tempdir.py:160
#, python-format
msgid "Using temporary directory %s"
msgstr "Utilizando directorio temporal %s"

#: ../duplicity/tempdir.py:204
#, python-format
msgid "Registering (mktemp) temporary file %s"
msgstr "Registrando archivo temporal (mktemp) %s"

#: ../duplicity/tempdir.py:226
#, python-format
msgid "Registering (mkstemp) temporary file %s"
msgstr "Registrando archivo temporal (mkstemp) %s"

#: ../duplicity/tempdir.py:258
#, python-format
msgid "Forgetting temporary file %s"
msgstr "Olvidando el archivo temporal %s"

#: ../duplicity/tempdir.py:261
#, python-format
msgid "Attempt to forget unknown tempfile %s - this is probably a bug."
msgstr ""
"Intentando olvidar un archivo temporal desconocido %s. Esto es posiblemente "
"un error."

#: ../duplicity/tempdir.py:280
#, python-format
msgid "Removing still remembered temporary file %s"
msgstr "Eliminar archivo temporal todavía recordado %s"

#: ../duplicity/tempdir.py:283
#, python-format
msgid "Cleanup of temporary file %s failed"
msgstr "La limpieza del archivo temporal %s falló"

#: ../duplicity/tempdir.py:288
#, python-format
msgid "Cleanup of temporary directory %s failed - this is probably a bug."
msgstr ""
"La limpieza del directorio temporal %s falló. Esto posiblemente sea un error."

#: ../duplicity/util.py:144
#, python-format
msgid "IGNORED_ERROR: Warning: ignoring error as requested: %s: %s"
msgstr "IGNORED_ERROR: Aviso: ignorando error tal como se pidió: %s: %s"

#: ../duplicity/util.py:211
#, python-format
msgid "Releasing lockfile %s"
msgstr "Publicando fichero de candado %s"

#~ msgid ""
#~ "Warning: exclude-device-files is not the first selector.\n"
#~ "This may not be what you intended"
#~ msgstr ""
#~ "Aviso: exclude-device-files no es el primer selector.\n"
#~ "Puede no ser la opción elegida."

#~ msgid ""
#~ "For certificate verification with python 2.7.8 or earlier a cacert "
#~ "database\n"
#~ "file is needed in one of these locations: %s\n"
#~ "Hints:\n"
#~ "  Consult the man page, chapter 'SSL Certificate Verification'.\n"
#~ "  Consider using the options --ssl-cacert-file, --ssl-no-check-"
#~ "certificate ."
#~ msgstr ""
#~ "Para verificación de certificado con python 2.7.8 o anterior se requiere "
#~ "un\n"
#~ "archivo de base de datos cacert en alguna de estas ubicaciones: %s\n"
#~ "Sugerencias:\n"
#~ "  Consulte la página man, capítulo «SSL Certificate Verification»\n"
#~ "  Considere el uso de las opciones --ssl-cacert-file, --ssl-no-check-"
#~ "certificate."

#~ msgid "MultiBackend: list from %s: %s"
#~ msgstr "MultiBackend: lista de %s: %s"
